apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project-ecr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-project-ecr
  template:
    metadata:
      labels:
        app: java-project-ecr
    spec:
      containers:
      - name: java-project-ecr
        image: public.ecr.aws/j4x0w9z8/java-project-ecr:latest
        ports:
        - containerPort: 8080
