apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydeploy
    spec:
      containers:
      - image: 340752798567.dkr.ecr.ap-south-1.amazonaws.com/java-project-ecr:latest
        name: java-project-ecr
        ports:
        - containerPort: 8080
        resources: {}
status: {}
