apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-final
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-final
  template:
    metadata:
      labels:
        app: jenkins-final
    spec:
      containers:
      - name: jenkins-final
        image: 340752798567.dkr.ecr.ap-south-1.amazonaws.com/java-project-ecr:latest
        ports:
        - containerPort: 8080
